Add metadata to install-config and provide CIS CRN through it
openshift-powervs/installer pull request #52
Opened 2021-08-28 02:06 UTC by mjturek

2021-08-30 21:37 UTC, mjturek commented
Okay this patch seems to work as long as you export IC_API_KEY

2021-09-03 00:59 UTC, clnperez commented
Ah, so it looks like, if users don't have `IC_API_KEY` set, this doesn't work: https://github.com/openshift-powervs/installer/blob/add-ipi/pkg/asset/installconfig/ibmcloud/client.go#L82 

I hadn't thought we'd have to require users to set this. Also we'd planned on allowing users to set other vars that have been supported in the past, or having their key stored on disk.  (fyi @mkumatag )

Is this what @23TNC was talking about having to export to an env var if it wasn't set?

2021-09-03 13:25 UTC, mjturek commented
@clnperez yep, this is the issue Cory was talking about. The way @23TNC is handling this is setting `IC_API_KEY` using `os.setenv()`. We can do that here as well to ensure that it's set properly. Correct me if I'm wrong @mkumatag but last call you agreed this solution was sufficient

2021-09-03 15:38 UTC, clnperez commented
Can you also add this CRN value in to the Metadata in pkg/asset/cluster/powervs/powervs.go and set it there?

2021-09-03 20:06 UTC, mjturek commented
> Can you also add this CRN value in to the Metadata in pkg/asset/cluster/powervs/powervs.go and set it there?

Good catch! Done!

2021-09-10 18:19 UTC, clnperez requested changes
LGTM, except for a grammar nit

2021-09-10 18:19 UTC, clnperez commented on pkg/asset/installconfig/powervs/metadata.go
> +// does not need to be user-supplied (e.g. because it can be retrieved
nit: does not need => do not ned

2021-09-10 18:41 UTC, mjturek commented on pkg/asset/installconfig/powervs/metadata.go
> +// does not need to be user-supplied (e.g. because it can be retrieved
Came from a copy paste but can fix :)

2021-09-10 19:20 UTC, merged