Added validation for CredentialMode
openshift-powervs/installer pull request #86
Opened 2021-12-02 13:55 UTC by bkhadars

2021-12-07 12:24 UTC, bkhadars commented
/cc @clnperez

2021-12-07 23:18 UTC, clnperez commented
lgtm
requesting a review from @mkumatag

2021-12-08 05:00 UTC, mkumatag requested changes
overall lgtm except for one minor comment for the test case addition.

2021-12-08 05:00 UTC, mkumatag commented on pkg/types/validation/installconfig_test.go
> +			expectedError: `^credentialsMode: Unsupported value: "Mint": supported values: "Manual"$`,
do we have a testcase for the happy path by mentioning manual mode?

2021-12-13 17:27 UTC, merged