Added Powervs platfrom permission check
openshift-powervs/installer pull request #88
Opened 2021-12-07 12:14 UTC by bkhadars

2021-12-07 13:13 UTC, bkhadars commented
/cc @clnperez

2021-12-07 21:41 UTC, clnperez requested changes
there are three places that need some form of account validation before an install can move forward:
- pkg/asset/installconfig/platformcredscheck.go: we just called GetSession(), and that's about what all the other providers do so that's fine.
pkg/asset/installconfig/platformpermscheck.go: checks to make sure the credentials provided actually have permission to create resources (what you checked in this PR)
pkg/asset/installconfig/platformprovisioncheck.go: checks xyz, and right now all we do is again call GetSession (inside of `ValidateForProvisioning()`). we should also do what some of the other providers do, and check the public DNS

Do you want to update pkg/asset/installconfig/platformprovisioncheck.go in a follow-up PR and just address the comments I made inline? Or you can also add that here.  I'm fine with either.

2021-12-07 21:41 UTC, clnperez commented on pkg/asset/installconfig/powervs/platform.go
> +		return fmt.Errorf("account is Trial/Lite account, doesn't have permission to create powervs instance/vm's")
can you change this to "account type of Trial/Lite cannot be used to provision Power VS resources."

2021-12-07 21:41 UTC, clnperez commented on pkg/asset/installconfig/platformpermscheck.go
> +			return errors.Wrap(err, "Powervs permission validation failed")
i think the error you've got in ValidateAccountPermissions is good so you can just pass that straight through instead of adding to it here:

```
if err != nil {
     return err
}
```

2021-12-07 21:41 UTC, clnperez commented on pkg/asset/installconfig/powervs/client.go
> +	// Frab variables from the users environment
typo = Frab=>Grab; users=>user's

2021-12-07 21:41 UTC, clnperez commented on pkg/asset/installconfig/powervs/client.go
> +type User struct {
Can we rename this to something like IBMCloudUser and the above Client to IBMCloudClient?

2021-12-08 23:23 UTC, clnperez commented
@bkhadars ping

2021-12-09 12:31 UTC, bkhadars commented on pkg/asset/installconfig/powervs/platform.go
> +		return fmt.Errorf("account is Trial/Lite account, doesn't have permission to create powervs instance/vm's")
> 

Will raise new PR for adding the DNS check and other's

2021-12-09 12:35 UTC, bkhadars commented
> there are three places that need some form of account validation before an install can move forward:
> 
> * pkg/asset/installconfig/platformcredscheck.go: we just called GetSession(), and that's about what all the other providers do so that's fine.
> * pkg/asset/installconfig/platformpermscheck.go: checks to make sure the credentials provided actually have permission to create resources (what you checked in this PR)
> * pkg/asset/installconfig/platformprovisioncheck.go: checks xyz, and right now all we do is again call GetSession (inside of `ValidateForProvisioning()`). we should also do what some of the other providers do, and check the public DNS
> 
> Do you want to update pkg/asset/installconfig/platformprovisioncheck.go in a follow-up PR and just address the comments I made inline? Or you can also add that here. I'm fine with either.



> there are three places that need some form of account validation before an install can move forward:
> 
> * pkg/asset/installconfig/platformcredscheck.go: we just called GetSession(), and that's about what all the other providers do so that's fine.
> * pkg/asset/installconfig/platformpermscheck.go: checks to make sure the credentials provided actually have permission to create resources (what you checked in this PR)
> * pkg/asset/installconfig/platformprovisioncheck.go: checks xyz, and right now all we do is again call GetSession (inside of `ValidateForProvisioning()`). we should also do what some of the other providers do, and check the public DNS
> 
> Do you want to update pkg/asset/installconfig/platformprovisioncheck.go in a follow-up PR and just address the comments I made inline? Or you can also add that here. I'm fine with either.

WIll raise new PR with the DNS check and will check other Provider validation as well

2021-12-09 20:54 UTC, clnperez commented
looks like the CI check failed, and you may need to re-run `go mod tidy` for a newer version of go.mod.

2021-12-13 09:38 UTC, bkhadars commented
> looks like the CI check failed, and you may need to re-run `go mod tidy` for a newer version of go.mod.

fixed

2021-12-13 17:22 UTC, clnperez commented
looks good. you ran through a cluster create scenario with this i'm assuming?

2021-12-13 20:17 UTC, merged